# configuration for "master" branch
-
  configuration: Release
  branches:
      only:
        - master
  version: 1.0.{build}
  environment:
    GITHUB_USERNAME:
      secure: GSAHxMHKjqQYnQRhOtw7EQ==
    GITHUB_TOKEN:
      secure: 2UYPgWolkgPkTWaF0PbxbinjALupedRCsiFaPOXvtB9BzzdzyUb6TFkh+DWA5zNv
  build_script:
  - ps: ./build.ps1
  artifacts:
  - path: artifacts/*
  test: off
  cache:
  - packages -> src\**\packages.config
  - tools -> .build/tools.cake
  
# configuration for "develop" branch
-
  configuration: Development
  branches:
      except:
          - master          
  version: 1.0.{build}
  skip_branch_with_pr: true
  build_script:
  - ps: ./build.ps1
  artifacts:
  - path: artifacts/*
  test: off
  cache:
  - packages -> src\**\packages.config
  - tools -> .build/tools.cake

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Development