//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("DataEntry.Cli")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-build-GH-2.1+7.Branch.build/GH-2.Sha.c894e13b32107b31332f247d8e0c9bbb7ee7387d")]
[assembly: AssemblyCopyright("Copyright (c) Eugene Sergueev")]

